//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Зачёт
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticlesElis
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Image { get; set; }
    
        public virtual DescrElis DescrElis { get; set; }
    }
}
