//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Зачёт
{
    using System;
    using System.Collections.Generic;
    
    public partial class DescrElis
    {
        public int ID { get; set; }
        public string Description { get; set; }
    
        public virtual ArticlesElis ArticlesElis { get; set; }
    }
}
